name: clean_arch
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter_bloc: ^9.0.0
  flutter:
    sdk: flutter
  equatable: ^2.0.7   
  bloc: ^9.0.0
  shared_preferences: ^2.4.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
